; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -mtriple=riscv32 -mattr=+m -mattr=+xcorevaluv2 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s
; RUN: llc -O0 -mtriple=riscv32 -mattr=+m -mattr=+xcorevalu -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @exths(i16 %a) {
; CHECK-LABEL: exths:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $x11 killed $x10
; CHECK-NEXT:    cv.exths a0, a0
; CHECK-NEXT:    ret
  %1 = sext i16 %a to i32
  ret i32 %1
}
